### ISSUE TITLE
Failed to compile with Exception.h in Ubuntu 22.04

### ISSUE THREAD

**Issue by simk0024** [mchehab/zbar#254]
expected identifier before string constant and other errors are encountered while compile in Ubuntu 22.04.
zbar was installed `sudo apt install libzbar-dev libzbar0`
any advice?

Errors:
```
/usr/include/zbar/Exception.h:76:5: error: expected identifier before string constant
   76 |     UnsupportedError (const void *obj)
      |     ^~~~~~~~~~~~~~~~
/usr/include/zbar/Exception.h:76:5: error: expected ‘,’ or ‘...’ before string constant
In file included from /usr/include/zbar.h:1644,
                 from /home/sg-atcoe-23761/ws_scannerbot/src/scanning_slh/scannerbot/include/scannerbot/zbar_scanner.hpp:3,
                 from /home/sg-atcoe-23761/ws_scannerbot/src/scanning_slh/scannerbot/include/scannerbot/scannerbot_node.hpp:17,
                 from /home/sg-atcoe-23761/ws_scannerbot/src/scanning_slh/scannerbot/src/scannerbot_node.cpp:1:
/usr/include/zbar/Exception.h: In member function ‘int zbar::UnsupportedError::Error(int)’:
/usr/include/zbar/Exception.h:77:11: error: only constructors take member initializers
   77 |         : Exception(obj)
      |           ^~~~~~~~~
/usr/include/zbar/Exception.h:77:21: error: ‘obj’ was not declared in this scope; did you mean ‘_obj’?
   77 |         : Exception(obj)
      |                     ^~~
      |                     _obj
In file included from /usr/local/include/ZXing/Result.h:14,
                 from /usr/local/include/ZXing/ReadBarcode.h:10,
                 from /home/sg-atcoe-23761/ws_scannerbot/src/scanning_slh/scannerbot/include/scannerbot/scannerbot_node.hpp:11,
                 from /home/sg-atcoe-23761/ws_scannerbot/src/scanning_slh/scannerbot/src/scannerbot_node.cpp:1:
/usr/include/zbar/Exception.h: In function ‘std::exception zbar::throw_exception(const void*)’:
/usr/include/zbar/Exception.h:166:15: error: ‘Error’ has not been declared
  166 |         throw UnsupportedError(obj);
      |               ^~~~~~~~~~~~~~~~
/usr/include/zbar/Exception.h:166:15: error: no matching function for call to ‘std::__cxx11::basic_string<char>::basic_string(const void*&)’
  166 |         throw UnsupportedError(obj);
      |               ^~~~~~~~~~~~~~~~
```

**Comment by simk0024** [comment]
My bad, I was trying to compile a program which use ZBar and ZXing at the same times, which caused the conflict of some declaration and functions. 
Compilation works when I compile 2 libraries separately before used as dependencies in the main program.
