### ISSUE TITLE
moc_zbarcam_qt.h: No such file or directory

### ISSUE THREAD

**Issue by za3k** [mchehab/zbar#228]
```
autoreconf -vfi && ./configure && make clean && make
[...]
zbarcam/zbarcam-qt.cpp:1009:10: fatal error: moc_zbarcam_qt.h: No such file or directory
 1009 | #include "moc_zbarcam_qt.h"
```

Trying to do a clean build from a freshly checked out copy of zbar is currently not working for me:

I'm not sure what this is, but I can provide a little brute force. Bisecting, it was introduced in commit c95186c69dcbe6a7acb7ec4d5e5b5f1b8dc20f20

````
7758ff6faba1d13876386e3a39dcec1f71c5bebc (2021-09-07): FAIL
ecca1d16eec189c03b6841b14b2fea635d974f4c (2022-05-29): FAIL
55c9a5e934cde04982e24d6e6d6b7a658bfe39ad: FAIL
093aa5df6b550635a001458ad8b0e38b47a77be5: FAIL
aba7f339c7f5a163c2196be060119684d174ac79: FAIL
c95186c69dcbe6a7acb7ec4d5e5b5f1b8dc20f20: FAIL
4e0f618b54af060fc3516acfb34b6023ed064620: OK
4084cd6707e80b0c03deed39cf419e6ed3e4c5f2 (2021-03-15): OK
468f6bda627d683b3f40dbaf242c158409666f7e (2021-03-13): OK
0.23.92 (2021-02-16): OK
```

**Comment by dagmcr** [comment]
I have the same issue. Are we missing some dependency?

The problem seems to be with `Qt5.pc`. It doesn't exist in my case.

```shell
...
checking for Qt5Core >= 5 Qt5Gui >= 5 Qt5Widgets >= 5.0 Qt5X11Extras >= 5.0...  
yes

Package Qt5 was not found in the pkg-config search path.
Perhaps you should add the directory containing `Qt5.pc'
to the PKG_CONFIG_PATH environment variable
No package 'Qt5' found

Package Qt5 was not found in the pkg-config search path.
Perhaps you should add the directory containing `Qt5.pc'
to the PKG_CONFIG_PATH environment variable
No package 'Qt5' found

configure: using Qt version 
configure: using moc from 

checking for javac... 
```

I have `Qt5Core.pc` among others (see below). But `pkg-config Qt5Core --variable=moc` return is empty. This is because it does not provide `moc`. Variables provided are:

> Line [678](https://github.com/mchehab/zbar/blob/master/configure.ac#L678) `[MOC=pkg-config Qt5 --variable=moc`

```shell
root@7e156cd77b55:/build/workspace/sources/zbar# pkg-config Qt5Core --print-variables
exec_prefix
host_bins
includedir
libdir
pcfiledir
prefix
qt_config
```

And here all the *.pc files I have:

```
/build/tmp/work/znver1-poky-linux/zbar/0.23.92+git999-r0/recipe-sysroot/usr/lib/pkgconfig/Qt5OpenGL.pc
/build/tmp/work/znver1-poky-linux/zbar/0.23.92+git999-r0/recipe-sysroot/usr/lib/pkgconfig/Qt5Xml.pc
/build/tmp/work/znver1-poky-linux/zbar/0.23.92+git999-r0/recipe-sysroot/usr/lib/pkgconfig/Qt5Network.pc
/build/tmp/work/znver1-poky-linux/zbar/0.23.92+git999-r0/recipe-sysroot/usr/lib/pkgconfig/Qt5X11Extras.pc
/build/tmp/work/znver1-poky-linux/zbar/0.23.92+git999-r0/recipe-sysroot/usr/lib/pkgconfig/Qt5Core.pc
/build/tmp/work/znver1-poky-linux/zbar/0.23.92+git999-r0/recipe-sysroot/usr/lib/pkgconfig/Qt5PrintSupport.pc
/build/tmp/work/znver1-poky-linux/zbar/0.23.92+git999-r0/recipe-sysroot/usr/lib/pkgconfig/Qt5Test.pc
/build/tmp/work/znver1-poky-linux/zbar/0.23.92+git999-r0/recipe-sysroot/usr/lib/pkgconfig/Qt5Gui.pc
/build/tmp/work/znver1-poky-linux/zbar/0.23.92+git999-r0/recipe-sysroot/usr/lib/pkgconfig/Qt5Sql.pc
/build/tmp/work/znver1-poky-linux/zbar/0.23.92+git999-r0/recipe-sysroot/usr/lib/pkgconfig/Qt5Concurrent.pc
/build/tmp/work/znver1-poky-linux/zbar/0.23.92+git999-r0/recipe-sysroot/usr/lib/pkgconfig/Qt5DBus.pc
/build/tmp/work/znver1-poky-linux/zbar/0.23.92+git999-r0/recipe-sysroot/usr/lib/pkgconfig/Qt5Widgets.pc
/build/tmp/work/znver1-poky-linux/zbar/0.23.92+git999-r0/recipe-sysroot/usr/lib/pkgconfig/Qt5OpenGLExtensions.pc
/build/tmp/work/znver1-poky-linux/zbar/0.23.92+git999-r0/recipe-sysroot/usr/lib/pkgconfig/Qt5Svg.pc
```
